name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out code
        uses: actions/checkout@v2
  
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: check for hello.ts.net in netmap
        run: echo "ntza" > ntza.txt
      # - name: Deploy using ssh
      #   uses: appleboy/ssh-action@master
      #   env:
      #     TOKEN: ${{ secrets.TOKEN }}
      #     MONGO: ${{ secrets.MONGO }}
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     envs: TOKEN,MONGO
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       cd ~/DynoW-bot
      #       git pull origin main
      #       ./script.sh
            
